repository:
  name: obsidian-auto-periodic-notes
  description: Creates new periodic notes automatically in the background and allows these to be pinned in your open tabs, requires the "Periodic Notes" plugin.
  topics: obsidian, typescript, plugin, notes, pkm
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
labels:
  - name: "ğŸ“š documentation"
    color: 0075ca
    description: Improvements or additions to documentation
  - name: "ğŸ› bug"
    color: d73a4a
    description: Something isn't working
  - name: "â¬†ï¸ dependencies"
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: "âš¡ enhancement"
    color: a2eeef
    description: Update to existing feature or request
  - name: "âœ¨ feature"
    color: 22dd53
    description: Brand new feature or idea
  - name: "â›”ï¸ invalid"
    color: e4e669
    description: This doesn't seem right
  - name: "ğŸ§‘â€ğŸ¤â€ğŸ§‘ duplicate"
    color: cfd3d7
    description: This issue or pull request already exists
  - name: "â“ question"
    color: d876e3
    description: More information is needed
  - name: "ğŸ¤¦â€â™‚ï¸ wontfix"
    color: ffffff
    description: This won't be worked on
  - name: "ğŸš¨ tests"
    color: fcb1a8
    description: Updates or adds tests
  - name: "ğŸ”¨ task"
    color: 4346cc
    description: Technical or build task
milestones:
  - title: Auto Periodic Notes Initial Release
    description: Everything needed for the initial release of the plugin, including all functionality.
    state: open
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ['Test']
      enforce_admins: false
      restrictions:
        apps: []
        users: []
        teams: []
