name: Build

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Dependencies
        run: |
          npm i
      - name: Get Latest Version
        id: latest
        uses: gregziegan/fetch-latest-release@v2.0.0
      - name: Calculate Next Version
        id: calculate
        uses: paulhatch/semantic-version@v5.3.0
        with:
          version_format: "${major}.${minor}.${patch}"
      - name: Determine Next Version
        if: ${{ contains(steps.latest.outputs.name, '.') }}
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ contains(steps.latest.outputs.name, '.') }}
          if_true: ${{ steps.calculate.outputs.version }}
          if_false: '0.0.1'
      - name: Remove Leading "v" from Latest Version
        if: ${{ contains(steps.latest.outputs.name, '.') }}
        id: latest_clean
        run: |
          export version=$(echo ${{ steps.latest.outputs.name }} | sed 's/^v//')
          echo ::set-output name=name::$version
      - name: Update Version in Files
        if: ${{ contains(steps.latest.outputs.name, '.') }}
        uses: datamonsters/replace-action@v2
        with:
          files: 'package.json'
          replacements: "${{ steps.latest_clean.outputs.name }}=${{ steps.version.outputs.value }}"
      - name: Update Version Script
        if: ${{ contains(steps.latest.outputs.name, '.') }}
        run: VERSION=${{ steps.version.outputs.value }} npm run version
      - name: File Save Delay
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'
      - name: Commit Version Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update version to v${{ steps.version.outputs.value }}"
      - name: Build
        run: npm run build
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: 'main.js,manifest.json'
          draft: false
          makeLatest: true
          tag: v${{ steps.version.outputs.value }}
          name: v${{ steps.version.outputs.value }}
